version: "3.8"
services:
    client:
        ports:
            - 5001:8080
        build: .
        volumes:
            - ./src/:/code/src # connect the source code to the container for live-reloads during development
        entrypoint: [ "npm", "run", "dev-server" ]
